package cn.kona;

import cn.kona.socket.Server;

/**
 * Generated by ryplat | Wed Sep 13 14:17:33 CST 2017
 */
public class App {

    public static void main(String[] args) throws Exception {
        Server server = Kona.tcp();
        server.listen(8888);
    }
}
