package cn.kona;

import cn.kona.transport.Cell;
import cn.kona.transport.Pipeline;
import cn.kona.transport.impl.Acceptor;
import java.net.InetSocketAddress;
import java.nio.channels.ServerSocketChannel;
import org.jetbrains.annotations.NotNull;

/**
 * Generated by ryplat | Wed Sep 13 14:17:33 CST 2017
 */
public class App {

    public static void main(String[] args) throws Exception {
        InetSocketAddress address = new InetSocketAddress(9999);
        ServerSocketChannel channel = ServerSocketChannel.open();
        channel.socket().bind(address);
        Pipeline pipeline = new Pipeline();
        pipeline.addCells(new TestCell("1"), new TestCell("2"), new TestCell("3"));
        Acceptor acceptor = new Acceptor(pipeline);
        acceptor.registerChannel(channel, "boss");
        acceptor.run();
    }

    static class TestCell implements Cell {

        private String num;

        public TestCell(String num) {
            this.num = num;
        }

        @NotNull
        @Override
        public Object make(@NotNull Object data) {
            System.out.println("added " + num + "data " + data);
            return "added " + num + "data " + data;
        }
    }
}
